import type { Metadata } from "next";
import { Logo } from "../components/logo";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <div className="min-h-screen flex items-center justify-center flex-col gap-8">
    <Logo />
   {children}
   </div>
  );
}
