import type { Metadata } from "next";
import { Logo } from "@components/logo";
import { HomeBtn } from "@components/ui/home-btn";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
   <div className="min-h-screen flex items-center justify-center flex-col gap-8 relative">
    <HomeBtn />
    <Logo />
   {children}
   </div>
  );
}
